fake:
	python fakeborrowings.py bagofsounds --brate 5 --output "../output"
	python fakeborrowings.py bagofsounds --brate 10 --output "../output"
	python fakeborrowings.py bagofsounds --brate 20 --output "../output"
	python fakeborrowings.py markovdual --brate 5 --output "../output"
	python fakeborrowings.py markovdual --brate 10 --output "../output"
	python fakeborrowings.py markovdual --brate 20 --output "../output"
	python fakeborrowings.py neuraldual --brate 5 --output "../output"
	python fakeborrowings.py neuraldual --brate 10 --output "../output"
	python fakeborrowings.py neuraldual --brate 20 --output "../output"

